# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

I suggest you implement *constraint satisfaction* as it is described in the unit material. You can use the code you have previously been given as a guide. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%).

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [62]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [71]:
import numpy as np


class SudokuState:
    """Representation of Sudoku board and methods to solve it and check whether it can be solved"""

    def __init__(self, sudoku, possible=None):
        """
        Constructor for the SudokoState

        :param sudoku: The 2D numpy array represeting the Sudoku grid
        :param possible: Default - None, when no prior state has been used
        """

        self.final_values = sudoku  # 2d np array
        self.mc_len = 9  # most constrained cells len
        self.mc_row, self.mc_col = 0, 0  # most constrained cells row, col
        if possible is None:
            self.possible_values = [[i for i in range(0, 9)] for _ in range(0, 9)]
            self.build_possible_values()
        else:
            self.possible_values = possible

    def build_possible_values(self):
        for row in range(0,9):
            for col in range(0,9):
                if self.final_values[row,col] != 0:
                    self.possible_values[row][col] = []
                else:
                    self.possible_values[row][col] = [i for i in range(1, 10)]


    def initial_propagate(self):
        """
        Iterates through the grid checking whether it can be solved and propogated the values placed there already

        :return: True if it can be solved. False if not
        """

        for row in range(0, 9):
            for col in range(0, 9):
                if self.final_values[row, col] != 0:  # if the values have already been placed propagate them
                    if self.check_board(row, col):
                        self.propagate(row, col)
                    else:
                        return False
                else:  # if there is no value in this position then no need to propagate %%!
                    continue
        return True

    def check_board(self, row, col):
        """
        Checks whether the board is solvable i.e. does it go against any of the constraints off the bat

        :param row: row index of a cell to be checked
        :param col: col index of a cell to be checked
        :return: True if solvable False if not
        """

        number = self.final_values[row, col]
        for i in range(0, 9):
            if self.final_values[row, i] == number and i != col:  # checks the horizontal
                return False
            if self.final_values[i, col] == number and i != row:  # checks the vertical
                return False
        # checks the box
        row0 = (row // 3) * 3
        col0 = (col // 3) * 3
        for i in range(0, 3):
            for j in range(0, 3):
                if number == self.final_values[row0 + i, col0 + j] and (row0 + i != row and col0 + i != col):
                    return False
        return True

    def is_invalid(self):
        """This partial state is invalid if any cell has the value 0 and has 0 possible moves left"""

        for row in range(0, 9):
            for col in range(0, 9):
                if self.final_values[row, col] == 0 and len(self.possible_values[row][col]) == 0:
                    return True
        return False

    def is_goal(self):
        """This compares each cell value with 0 - meaning it is incomplete"""

        for row in range(0, 9):
            for col in range(0, 9):
                if self.final_values[row, col] == 0:
                    return False
        return True
        # return all(all(row != 0) for row in self.final_values)

    def get_singleton_cells(self):
        """Returns the cells which have no final value but exactly 1 possible value"""

        singletons = []
        for row in range(0, 9):
            for col in range(0, 9):
                if len(self.possible_values[row][col]) == 1 and self.final_values[row, col] == 0:
                    singletons.append([row, col])
        return singletons

    def propagate(self, row, col):
        """
        Propagates a particular row and columns value throughout its domain, and changes
        the most constrained cells values.

        :param row: row of cell being propagated
        :param col: col of cell being propagated
        """

        number = self.final_values[row, col]
        self.possible_values[row][col] = []  # removing any possible values

        for i in range(0, 9):
            if number in self.possible_values[row][i]:  # checks the horizontal
                self.possible_values[row][i].remove(number)
                if 1 < len(self.possible_values[row][i]) < self.mc_len:
                    self.mc_len = len(self.possible_values[row][i])
                    self.mc_col = i
                    self.mc_row = row

            if number in self.possible_values[i][col]:  # checks the vertical
                self.possible_values[i][col].remove(number)
                if 1 < len(self.possible_values[i][col]) < self.mc_len:
                    self.mc_len = len(self.possible_values[i][col])
                    self.mc_col = col
                    self.mc_row = i
        # checks the box
        row0 = (row // 3) * 3
        col0 = (col // 3) * 3
        for i in range(0, 3):
            for j in range(0, 3):
                if number in self.possible_values[row0 + i][col0 + j]:
                    self.possible_values[row0 + i][col0 + j].remove(number)
                    if 1 < len(self.possible_values[row0 + i][col0 + j]) < self.mc_len:
                        self.mc_len = len(self.possible_values[row0 + i][col0 + j])
                        self.mc_col = col0 + j
                        self.mc_row = row0 + i

    def create_possible_copy(self):
        """
        Alternative method to deepcopy which takes up a large amount of computational time, creates a copy of the
        possible_values 3D list.

        :return: copy of possible_values
        """
        possible_copy = [[[] for _ in range(0, 9)] for _ in range(0, 9)]
        for row in range(0, 9):
            for col in range(0, 9):
                for values in self.possible_values[row][col]:
                    possible_copy[row][col].append(values)
        return possible_copy

    def set_value(self, row, col, val):

        """
        Checks that the value can be placed in the given row and col then creates new state and updates its
        final_values then propagates this change through possible_values. If there are any singletons left then
        fills them in and propagates them.

        :param row: The row index where the value should be placed
        :param col: The column index where the value should be placed
        :param val: The value that should be placed at the row/col index
        :return: state: the new state created
        """

        # checking the value can be placed there and raising an error if not a valid move
        if val not in self.possible_values[row][col]:
            raise ValueError(f"{val} is not a valid choice for position: {row},{col}")

        # creates copies of possible moves and final values and creates new state
        possible_copy = self.create_possible_copy()
        final_copy = self.final_values.copy()
        state = SudokuState(final_copy, possible_copy)

        # assigns value to the new state
        state.final_values[row, col] = val
        state.propagate(row, col)

        singletons = state.get_singleton_cells()
        while len(singletons) > 0:
            col = singletons[0][1]
            row = singletons[0][0]

            state.final_values[row, col] = state.possible_values[row][col][0]
            state.propagate(row, col)
            singletons = state.get_singleton_cells()

        return state


def find_first_empty(state):
    """
    Finds the first empty cell in-case the Sudoku grid if the most constrained values
    do not pass the guard

    :param state: An unsolved Sudoku State
    :return: row, col: the indexes of the first unsolved value
    """
    for row in range(0, 9):
        for col in range(0, 9):
            if state.final_values[row][col] == 0:
                return row, col
    return -1, -1


def depth_first_search(state):
    """
    Performs a DFS on a SudokuState to solve it

    :param state: A SudokuState that requires solving
    :return: The solved SudokuState or None depending on whether it is solvable or not
    """
    # Guard for most constrained values
    if state.final_values[state.mc_row, state.mc_col] == 0:
        row = state.mc_row
        col = state.mc_col
    else:
        row, col = find_first_empty(state)

    values = state.possible_values[row][col]

    for value in values:
        new_state = state.set_value(row, col, value)
        if new_state.is_goal():
            return new_state
        if not new_state.is_invalid():
            deep_state = depth_first_search(new_state)
            if deep_state is not None and deep_state.is_goal():
                return deep_state

    return None


def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """

    partial_state = SudokuState(sudoku)
    if not partial_state.initial_propagate():
        return np.full((9, 9), -1)
    solved = depth_first_search(partial_state)
    if solved is None:
        return np.full((9, 9), -1)

    return solved.final_values


All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 30 seconds each on the test machine to count as successful, but you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [75]:
SKIP_TESTS = True

if not SKIP_TESTS:
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    very_start_time = time.process_time()
    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
    very_end_time = time.process_time()
    print("===========================\n")
    print("THE ENTIRE SOLUTION TAKES: ", very_end_time-very_start_time, " seconds")

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [76]:
import sys
import pathlib

fail = False;

if not SKIP_TESTS:
    fail = True;
    print("You must set the SKIP_TESTS constant to True in the cell above.")
    
p1 = pathlib.Path('./readme.txt')
p2 = pathlib.Path('./readme.md')
if not (p1.is_file() or p2.is_file()):
    fail = True;
    print("You must include a separate file called readme.txt or readme.md in your submission.")
    
p3 = pathlib.Path('./sudoku.ipynb')
if not p3.is_file():
    fail = True
    print("This notebook file must be named sudoku.ipynb")
    
if "sudoku_solver" not in dir():
    fail = True;
    print("You must include a function called sudoku_solver which accepts a numpy array.")
else: 
    sudoku = np.load("data/very_easy_puzzle.npy")[0]
    solution = np.load("data/very_easy_solution.npy")[0]

    if not np.array_equal(sudoku_solver(sudoku), solution):
        print("Warning:")
        print("Your sudoku_solver function does not correctly solve the first sudoku.")
        print()
        print("Your assignment is unlikely to get any marks from the autograder. While we will")
        print("try to check it manually to assign some partial credit, we encourage you to ask")
        print("for help on the forum or directly to a tutor.")
        print()
        print("Please use the readme file to explain your code anyway.")
    
if fail:
    print()
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
    print("assignment page, without changing any filenames.")
    print()
    print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [77]:
# This is a TEST CELL. Do not delete or change.